name: trep
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy=1.19.2
  - pandas=1.0.1
  - scipy=1.6.1
  - scikit-learn=0.24.2
  - matplotlib=3.6.0
  - statsmodels=0.12.2
  - joblib=1.2.0
  - bottleneck=1.3.2
  - psutil=5.9.0
  - pytorch=1.13.0
  - pytorch-cuda=11.8
  - tqdm
  - jupyterlab
  - pip:
      - umap==0.1.1
      - umap-learn==0.4.2
